# Generated by Django 5.0 on 2023-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=4)),
            ],
        ),
    ]
